# Generated by Django 4.1.7 on 2023-06-15 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
    ]
